### ISSUE TITLE
请问如何使用

### ISSUE THREAD

**Issue by amy-habor** [hyoau/zhihu-filter#1]

**Comment by hyoau** [comment]
这个插件有在 Chrome 商店发布哦，你可以查看一下 [link](https://chrome.google.com/webstore/detail/%E7%9F%A5%E4%B9%8E%E8%BF%87%E6%BB%A4%E5%99%A8/pjkopgmnbdlfnpeiipljmcapnhgffddc?hl=zh)~

**Comment by amy-habor** [comment]
> 

抱歉我没说清楚，我装好了插件，但是勾选了屏蔽匿名用户，但是首页还是会有匿名用户的回答
黑名单后边显示的也是0，但是我是有黑名单的

**Comment by hyoau** [comment]
估计是知乎修改了相关 div classname ╯︿╰

**Comment by amy-habor** [comment]
> 估计是知乎修改了相关 div classname ╯︿╰

看了一下现在回答的div 是叫ContentItem AnswerItem

我改了一下获取作者的部分，现在首次刷新时候加载的部分可以做到屏蔽匿名用户了，但是下拉加载更多的时候就不会触发filter.js，加载更多的时候是应该修改哪部分呢

**Comment by hyoau** [comment]
欸，我看 Google 最新的条款 manifest_version 2 已经无法继续安装了，你是怎么解决的呢？

**Comment by amy-habor** [comment]
> 欸，我看 Google 最新的条款 manifest_version 2 已经无法继续安装了，你是怎么解决的呢？

2.0的支持在23年移除，现在还能用

**Comment by hyoau** [comment]
原来如此~ 如果我没有理解错的话，是 filter.js line 19 中的 MutationSummary 因为知乎 div 变动而出现了问题...

**Comment by amy-habor** [comment]
> MutationSummary

zm-item-answer这个div不见了，现在问题的div应该是ContentItem AnswerItem
new MutationSummary 里边的queries参数里，zm-item-answer直接改成ContentItem AnswerItem后续会报错，我就给改成了ContentItem_AnswerItem，也不知道可不可以。另外一个_CommentItem_root_PQNS不清楚是做什么的，没有改。
modify_answer_num这个方法，因为我不知道里边的几个div现在是在哪的，所以我把这个方法的调用注掉了
这样子改完，下拉更新并不好用。。

**Comment by hyoau** [comment]
`ContentItem AnswerItem` 表示该 div 属于两个 class，是不能改成 `ContentItem_AnswerItem` 的，`_CommentItem_root_PQNS` 指的是评论区部分。好久不写前端了，咱们可以一起来研究一下怎么解决这个问题~

**Comment by amy-habor** [comment]
> `ContentItem AnswerItem` 表示该 div 属于两个 class，是不能改成 `ContentItem_AnswerItem` 的，`_CommentItem_root_PQNS` 指的是评论区部分。好久不写前端了，咱们可以一起来研究一下怎么解决这个问题~

原来是这样。

把回答的div名字改成AnswerItem
filter_answer()中获取who改为 var who = eval('(' + ele.dataset.zop + ')')["authorName"];
然后注掉modify_answer_num()方法的调用（因为不知道里边要的两个div现在对应的什么）
下拉加载就也会触发过滤了

不过filter_handler不知道怎么触发

**Comment by hyoau** [comment]
你可以 `pull request` 让我看一下具体你是怎么解决这个问题的哈~

**Comment by hyoau** [comment]
你提交的代码很好地的解决了这个问题！谢谢~
